### ISSUE TITLE
Need build/install instructions for macos

### ISSUE THREAD

**Issue by BradyWiseman** [nshttpd/oci-tools#15]
Trying to install this on macos as a non-go (no-go?) programmer.
Every invocation results in 
panic: runtime error: invalid memory address or nil pointer dereference

How do you run this thing?

**Comment by nshttpd** [comment]
It functions the same as the OCI CLI, but with somewhat more sane command and combination of data into a more useful output. You still have to setup the ~/.oci/config file just as you would with the OCI CLI.

**Comment by nshttpd** [comment]
binaries have also now been generated via CI/CD and can be found here on github.
